clear all;clc;
%system('module load fsl/6.0.2');

basedir = '/bcbl/home/public/DB/devtrajtract/DATA/BERTSOLARI';

% container='anatrois';
% version='4.5.3-7.3.2';
% analysis='analysis-01';

container='freesurferator';
version='0.2.0-7.4.1rc19';
analysis='analysis-control_points_02';

projPath = fullfile(basedir,'nifti','derivatives',...
    strcat(container,'_',version),analysis);

subSesList    = fullfile(projPath,'subSesList.txt');
opts          = detectImportOptions(subSesList);
opts = setvartype(opts,{'sub','ses','RUN','anat','dwi','func'},...
                       {'categorical',...
                       'categorical',...
                       'logical',...
                       'logical',...
                       'logical',...
                       'logical'});
ssl           = readtable(subSesList,opts); 
subs = unique(ssl.sub);
ssl = ssl(ssl.anat==true & ssl.RUN==true,:);
rows = unique(ssl(:,{'sub','ses'}));

% % Define ROIs list to merge and their merged name

ROIformat = '.nii.gz';

ROIlist = {{'Left-V1','Left-V2'},...
           {'Right-V1','Right-V2'},...
           {'Left-VLa','Left-VLp'},...
           {'Right-VLa','Right-VLp'},...
           {'L_Area_1','L_Area_2','L_Area_3a','L_Primary_Sensory_Cortex'},...
           {'R_Area_1','R_Area_2','R_Area_3a','R_Primary_Sensory_Cortex'},...
           {'ctx_lh_G_cingul-Post-dorsal','ctx_lh_G_cingul-Post-ventral'},...
           {'ctx_rh_G_cingul-Post-dorsal','ctx_rh_G_cingul-Post-ventral'},...
           {'Left-MDl','Left-MDm'},...
           {'Right-MDl','Right-MDm'},...
           {'Left-Basal-nucleus','Left-Lateral-nucleus'},...
           {'Right-Basal-nucleus','Right-Lateral-nucleus'}};
for rl = 1:length(ROIlist)
    ROIlist{rl} = append(ROIlist{rl},ROIformat);
end

mergedROInames = {'Left-V1_AND_Left-V2',...
                  'Right-V1_AND_Right-V2',...
                  'Left-VLN',...
                  'Right-VLN',...
                  'L_Area_1_AND_L_Area_2_AND_L_Area_3a_AND_L_Primary_Sensory_Cortex',...
                  'R_Area_1_AND_R_Area_2_AND_R_Area_3a_AND_R_Primary_Sensory_Cortex',...
                  'ctx_lh_G_cingul-Post-dorsal_AND_ctx_lh_G_cingul-Post-ventral',...
                  'ctx_rh_G_cingul-Post-dorsal_AND_ctx_rh_G_cingul-Post-ventral',...
                  'Left-MDl_AND_Left-MDm',...
                  'Right-MDl_AND_Right-MDm',...
                  'Left-Basal-nucleus_AND_Left-Lateral-nucleus',...
                  'Right-Basal-nucleus_AND_Right-Lateral-nucleus'};

if (length(ROIlist) ~= length(mergedROInames))
    error("Merged ROI names must contain ROI to merge");
end

%% Iterate through each subject in the list
for nr = 1:height(rows)
    sub = char(rows.sub(nr));
    ses = char(rows.ses(nr));
    
    subdir = fullfile(projPath,...
                      strcat('sub-',sub),...
                      strcat('ses-',ses));
    
    unzip(fullfile(subdir,'output','fs.zip'),fullfile(subdir,'output'));              
    
    ROIdir = fullfile(subdir,'output','fs','ROIs');
    niiFiles = dir(fullfile(ROIdir, '*.nii*'));
    
    ROIs = cell(1,length(niiFiles));
    for K = 1 : length(niiFiles)
      ROIs{K} = niiFiles(K).name;
    end
    
    % create tmpdirectory where to process ROI
    ROItmp = fullfile(subdir,'output','tmp','ROIs');
    if ~exist(ROItmp, 'dir')
        mkdir(ROItmp)
    end
    
    for rl = 1:numel(ROIlist)
        ROIs2merge = ROIlist{rl};
        if ~isequal(sum(ismember(ROIs2merge,ROIs)), numel(ROIs2merge))
            error('Missing some of these ROIs:\n %s\n',ROIs2merge{:})
        end
        % % % % %
        if numel(ROIs2merge) < 2
            error('You must have at least 2 ROIs to merge')
        elseif numel(ROIs2merge) == 2
            cmdFslmaths = append('fslmaths ',...
                                 fullfile(ROIdir,ROIs2merge{1}),...
                                 ' -add ',...
                                 fullfile(ROIdir,ROIs2merge{2}),' ',...
                                 fullfile(ROItmp,mergedROInames{rl}));
        elseif numel(ROIs2merge) == 3
            cmdFslmaths = append('fslmaths ',...
                                 fullfile(ROIdir,ROIs2merge{1}),...
                                 ' -add ',...
                                 fullfile(ROIdir,ROIs2merge{2}),...
                                 ' -add ',...
                                 fullfile(ROIdir,ROIs2merge{3}),' ',...
                                 fullfile(ROItmp,mergedROInames{rl}));
        elseif numel(ROIs2merge) == 4
            cmdFslmaths = append('fslmaths ',...
                                 fullfile(ROIdir,ROIs2merge{1}),...
                                 ' -add ',...
                                 fullfile(ROIdir,ROIs2merge{2}),...
                                 ' -add ',...
                                 fullfile(ROIdir,ROIs2merge{3}),...
                                 ' -add ',...
                                 fullfile(ROIdir,ROIs2merge{4}),' ',...
                                 fullfile(ROItmp,mergedROInames{rl}));
        end
        system(cmdFslmaths);
    end
    copyfile(fullfile(ROItmp,'*.nii.gz'),ROIdir);
    movefile(fullfile(subdir,'output','fs.zip'),...
           fullfile(subdir,'output','fs_orig.zip'));
    zip(fullfile(subdir,'output','fs.zip'),fullfile(subdir,'output','fs'));
    system(append('rm -rf ',fullfile(subdir,'output','fs')));
end